# Generated by Django 2.2.2 on 2019-07-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
