# Generated by Django 2.2.2 on 2019-07-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0002_requests_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('attendant_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('blood_group', models.CharField(max_length=4)),
                ('quantity', models.IntegerField()),
                ('hospital_name', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('status', models.IntegerField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Requests',
        ),
    ]
