# Generated by Django 2.2.2 on 2019-07-12 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0003_auto_20190712_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='b_request_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloodbankapp.BRequests'),
        ),
    ]
