# Generated by Django 2.2.2 on 2019-07-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0004_donors_b_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='blood_group',
            field=models.CharField(max_length=20),
        ),
    ]
