# Generated by Django 2.2.2 on 2019-07-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0006_auto_20190713_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brequests',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'approve'), (2, 'done')], max_length=50),
        ),
    ]
