# Generated by Django 2.2.2 on 2019-07-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0009_auto_20190713_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='brequests',
            name='the_donors',
            field=models.CharField(default='', max_length=300),
        ),
    ]
