# Generated by Django 2.2.2 on 2019-07-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0011_auto_20190713_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brequests',
            name='the_donors',
            field=models.CharField(default=' ', max_length=700),
        ),
    ]
