# Generated by Django 2.2.2 on 2019-07-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0013_auto_20190714_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='address',
            field=models.TextField(),
        ),
    ]
