# Generated by Django 2.2.2 on 2019-07-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0014_auto_20190714_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brequests',
            name='the_donors',
            field=models.CharField(default='none', max_length=700),
        ),
    ]
