# Generated by Django 2.2.2 on 2019-07-14 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0016_auto_20190714_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='b_request_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloodbankapp.BRequests'),
        ),
    ]
